### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ArjixWasTaken** [rushiiMachine/osu-safe#1]
does this work for lazer?
and also, can you maybe add the option to instead load a custom jpg/png?

**Comment by rushiiMachine** [comment]
1) its unfinished
2) this won't work with osu! anticheat due to dse
3) lazer is unsupported because there's no point; just fork and disable backgrounds

**Comment by ArjixWasTaken** [comment]
> lazer is unsupported because there's no point; just fork and disable backgrounds

too lazy to do that ngl
